import json
import shutil
from pathlib import Path

import pytest

from evalplane import mcp_server as m

EX = Path(__file__).parent.parent / "examples" / "support-refund"


def test_tools_work_without_mcp(tmp_path, monkeypatch):
    d = tmp_path / "ex"
    shutil.copytree(EX, d, ignore=shutil.ignore_patterns(".evalplane", "__pycache__"))
    monkeypatch.chdir(d)
    plan = json.loads(m.tool_plan())
    assert plan["tier"] == "T4" and any(r["id"].startswith("L3.tool.guard@") for r in plan["requirements"])
    cov = json.loads(m.tool_coverage())
    assert "counts" in cov and isinstance(cov["gaps"], list)
    assert "why:" in m.tool_explain("L3.tool.guard@issue_refund")
    assert m.tool_validate().startswith("ok: support-refund")
    assert m.tool_validate("missing.yaml").startswith("invalid")
    assert "Generated by" in m.tool_generate_preview() or m.tool_generate_preview().startswith("#")


def test_server_registers_tools():
    pytest.importorskip("mcp")
    server = m.build_server()
    assert server is not None
